export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const FETCH_ONE_MOVIE = 'FETCH_ONE_MOVIE';

export const EDIT_ONE_MOVIE_SUCCESS = 'EDIT_ONE_MOVIE_SUCCESS';
export const EDIT_ONE_MOVIE_ERROR = 'EDIT_ONE_MOVIE_ERROR';

export const DELETE_ONE_MOVIE_SUCCESS = 'DELETE_ONE_MOVIE_SUCCESS';